# Generated by Django 4.2.7 on 2023-12-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('account', models.CharField(max_length=50)),
                ('debit_card', models.BooleanField()),
                ('credit_card', models.BooleanField()),
                ('cheque_book', models.BooleanField()),
            ],
        ),
    ]
