# Generated by Django 4.2.7 on 2023-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
